stages:
  - test

pytest:
  stage: test
  image: python:latest
  before_script:
    - pip install -r requirements.txt
  script:
    - cd python
    - pytest
  only:
    changes:
      - "/python/**/*"
    refs:
      - develop

