stages:
  - compile
  - test
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  API_PROJECT_PATH: "api/"
  IMAGE: "eclipse-temurin:21-alpine"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

backend-compile:
  stage: compile
  image: $IMAGE
  script:
    - cd $API_PROJECT_PATH
    - ./gradlew assemble

backend-test:
  stage: test
  image: $IMAGE
  script:
    - cd $API_PROJECT_PATH
    - ./gradlew test --stacktrace --info
  artifacts:
    paths:
      - test.log
    expire_in: 1 day

backend-build:
  stage: build
  image: $IMAGE
  script:
    - cd $API_PROJECT_PATH
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*.jar


pytest:
  stage: test
  image: python:latest
  before_script:
    - pip install -r python/requirements.txt
  script:
    - cd python
    - pytest
  only:
    refs:
      - develop
