postgres-autostart:
  enabled: true

spring:
  autoconfigure:
    exclude:
      - 'org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration'
      #- 'org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration'
  main:
    allow-bean-definition-overriding: true
  mvc:
    dispatch-options-request: true
  batch:
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
    url: jdbc:postgresql://localhost:5432/dyntex-db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: '/api'

logging:
  level:
    cz: TRACE
#    org.springframework: TRACE
